export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILURE = 'GET_PRODUCT_BY_CATEGORY_FAILURE';

export const GET_CATEGORY = 'GET_CATEGORY';
export const SWITCH_LAYOUT = 'SWITCH_LAYOUT';