export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_IS_AUTHENTICATING = 'SET_IS_AUTHENTICATING';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const FROM_PAYMENT_LINK = 'FROM_PAYMENT_LINK';

export const SET_TOKENS = 'SET_TOKENS';