export const LOADING_RELATED_PRODUCTS = 'LOADING_RELATED_PRODUCTS';
export const GET_RELATED_PRODUCT = 'GET_RELATED_PRODUCT';
export const GET_RELATED_PRODUCT_SUCCESS = 'GET_RELATED_PRODUCT_SUCCESS';
export const GET_RELATED_PRODUCT_FAILURE = 'GET_RELATED_PRODUCT_FAILURE';
