export const COPY_BILLING_DETAILS = 'COPY_BILLING_DETAILS';
export const CURRENT_STEP = 'CURRENT_STEP';
export const SAVE_BILLING_DETAILS = 'SAVE_BILLING_DETAILS';
export const SAVE_DELIVERY_DETAILS = 'SAVE_DELIVERY_DETAILS';
