export const GET_HOME_PAGE_PRODUCTS = 'GET_HOME_PAGE_PRODUCTS';
export const GET_HOME_PAGE_PRODUCTS_SUCCESS = 'GET_HOME_PAGE_PRODUCTS_SUCCESS';
export const GET_HOME_PAGE_PRODUCTS_FAILURE = 'GET_HOME_PAGE_PRODUCTS_FAILURE';
export const LOADING_PRODUCTS = 'GETTING_CATEGORIES';
