// LANGUAGE SELECTION
export const SET_LANGUAGE = 'SET_LANGUAGE';

// CATEGORIES SECTION
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GETTING_CATEGORIES = 'GETTING_CATEGORIES';

// GET PRODUCTS VIA SEARCH FEATURE
export const LOADING_SEARCH = 'LOADING_SEARCH';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_FAILURE = 'GET_SEARCH_RESULTS_FAILURE';
