export const SET_LANGUAGE = 'SET_LANGUAGE';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GETTING_CATEGORIES = 'GETTING_CATEGORIES';
